### ISSUE TITLE
What is the proper way to install shiny server on a rasperry pi?

### ISSUE THREAD

**Issue by terenceltl** [rstudio/shiny-server#132]
Is this currently possible?

Tried compiling from source on both raspbian and ubuntu MATE. Compiling seemed fine but the shiny server wont start. The situation is similar to that described in this thread:

http://stackoverflow.com/questions/30668288/shiny-server-does-not-start-and-returns-trace-breakpoint-trap

Anyone got it to work? Thanks.

**Comment by trestletech** [comment]
Hi.

Unfortunately there's not a "proper" way since it's not officially supported.

However, I was able to get this working on a Ubuntu image and I just uploaded it. You can grab it from here: https://github.com/trestletech/RpiR#images Unfortunately it is an 8GB image -- I'm not sure the best way to package these.

Also it's unfortunately not very reproducible or well documented -- there were a variety of hacks I made to get it running, but Shiny Server does start up on boot on port 80 and run applications correctly.

Also be aware that this image is set to `run_as` root in `/etc/shiny-server/shiny-server.conf` so your Shiny applications will run as root (which is convenient if you're using RpiR to do anything on the GPIO pins, but otherwise is probably not what you want).

Let me know if you have any trouble accessing the image.

**Comment by terenceltl** [comment]
Thanks a bunch for sharing!

I am downloading it a home and will give it a test soon.
