### ISSUE TITLE
Shiny server process dies with "Uncaught exception: Error: kill ESRCH"

### ISSUE THREAD

**Issue by cubranic** [rstudio/shiny-server#151]
Shiny server pro 1.3.0.540 running on RHEL 7.1

The service died with the following info in /var/log/shiny-server.log:

```
[... 13:04:20.996] [WARN] shiny-server - Error gathering metrics: Error: Error collecting process metrics: mismatched lengths.
[... 13:04:40.858] [ERROR] shiny-server - Uncaught exception: Error: kill ESRCH
[... 13:04:40.859] [INFO] shiny-server - Stopping listener on http://0.0.0.0:80
[... 13:04:40.859] [INFO] shiny-server - Shutting down worker processes (with notification)
[... 13:04:40.860] [ERROR] shiny-server - Failed to kill process: kill ESRCH
[... 13:04:40.860] [INFO] shiny-server - Stopping child monitor process

/opt/shiny-server/main.min.js:301
Uncaught exception: "+a);process.emit("uncaughtException2",a);throw a;});proce
                                                                    ^
Error: kill ESRCH
    at errnoException (node.js:540:13)
    at process.kill (node.js:728:15)
    at null._onTimeout (/opt/shiny-server/main.min.js:150:434)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by trestletech** [comment]
Hi Davor. It looks like you're on our Pro product. Can you contact us through our Support channel and we'll make sure someone looks at this first thing Monday?

Thanks!

**Comment by cristian44** [comment]
Dear trestletech,
I'm using the basic version for evaluation purpose, installed on a RHEL 7.1 and I'm getting the same error as cubranic. The shiny-server has been installed at the end of July and it crashed 5 times till now.
At first, I thought it's TIMEOUT setting but I think that's not the case because this error happens random. 
Other people are reporting the same issue here: http://stackoverflow.com/questions/32864962/shiny-server-crashing-timeout-errors
Any advice would be much appreciated,
Cristian
