### ISSUE TITLE
"Page not found" after "sudo /opt/shiny-server/bin/deploy-example user-dirs"

### ISSUE THREAD

**Issue by imcry** [rstudio/shiny-server#236]
I got "Page not found" after running "sudo /opt/shiny-server/bin/deploy-example user-dirs".

But when I run "sudo /opt/shiny-server/bin/deploy-example default" again, everything back to normal.

**Comment by fereshtehRS** [comment]
@imcry This is expected since you are changing the hosting method. Please refer to this section of the Admin Guide for info on hoe `user_dirs` work.

But in short:
- Your applications must reside in /home/<username>/ShinyApps directory
- To access the apps, based on the configuration file from above, you need to use a URL such as this:

```
http://<hostname>:3838/<username>/<appname>
```

**Comment by imcry** [comment]
@fereshtehRS Thanks. Just realized it's my issue. Have closed it.
