### ISSUE TITLE
Failed to restart shiny-server.service: Unit not found.

### ISSUE THREAD

**Issue by diablo312** [rstudio/shiny-server#316]
I installed R and shiny server in REHL 7. R installation was successful but when I tried to installed shiny server this is the message I got and it says shiny server installed.

```
 /var/tmp/rpm-tmp.kIBODd: line 62: initctl: command not found
 /var/tmp/rpm-tmp.kIBODd: line 65: initctl: command not found
 Verifying  : shiny-server-1.5.1.834-1.x86_64                                                                                                                                 
 1/1

 Installed:
 shiny-server.x86_64 0:1.5.1.834-1
```

however when I try to `systemctl start/restart shiny-server ` it says: 
`Failed to restart shiny-server.service: Unit not found.`

I am not really sure what is going on. The .service file is missing in the system/systemd  path

**Comment by gaurbans** [comment]
I am having the same issue trying to install shiny-server on RHEL 7.4, and part of the problem seems to be with these lines of code in the file `shiny-server-1.5.3.838-rh5-x86_64.rpm` (shown at the bottom here). The first `if` condition is met, so `elif` doesn't get executed. I tried manually running the code chunk below, and also deleting `shiny-server.conf` from `/etc/init/`. I can now successfully enter the command `systemctl restart shiny-server` but the default app still doesn't appear in a browser when I try go to `http://<YOUR_AWS_PRIVATE_IP>:3838`. 
```
cp /opt/shiny-server/config/systemd/shiny-server.service /etc/systemd/system/
systemctl enable shiny-server
systemctl restart shiny-server
```

```
# add upstart profile, or init.d/systemd script and start the server
if test -d /etc/init/
then
   # remove any previously existing init.d based scheme
   service shiny-server stop 2>/dev/null
   rm -f /etc/init.d/shiny-server

   cp /opt/shiny-server/config/upstart/shiny-server.conf /etc/init/
   initctl reload-configuration
   initctl stop shiny-server 2>/dev/null
   sleep 1
   initctl start shiny-server
elif [ "$RH_VER" == "7" ]
then
   cp /opt/shiny-server/config/systemd/shiny-server.service /etc/systemd/system/
   systemctl enable shiny-server
   systemctl restart shiny-server
else
   if test -e /etc/SuSE-release
   then
      cp /opt/shiny-server/config/init.d/suse/shiny-server /etc/init.d/
   else
      cp /opt/shiny-server/config/init.d/redhat/shiny-server /etc/init.d/
   fi

   chmod +x /etc/init.d/shiny-server
   chkconfig --add shiny-server
   service shiny-server stop 2>/dev/null
   sleep 1
   service shiny-server start
fi
```

**Comment by alandipert** [comment]
@diablo312 it looks like you installed an old version, can you try with `shiny-server-1.5.3.838-rh5-x86_64.rpm`?

You can get it from here: https://download3.rstudio.org/centos5.9/x86_64/shiny-server-1.5.3.838-rh5-x86_64.rpm

**Comment by alandipert** [comment]
@gaurbans I can see why the installer would fail, because it seems to rely on the fact that `upstart` isn't installed on RH 7 systems, but on yours it looks like it might be, since `/etc/init` exists. Perhaps you installed upstart manually, or another 3rd party package that relied on it?

It looks like your startup issue might be unrelated to the startup problem, since `systemctl` now works for you. Can you provide your `/var/log/shiny-server.log`? It could shed some light.

**Comment by gaurbans** [comment]
@alandipert I got it to work now. Not sure what was the issue the first time, it may have to do with the AWS environment I was in.

**Comment by diablo312** [comment]
@alandipert I tried with the new version still the same issue. I noticed that the shiny-server.service file was missing in etc/systemd/sytem/ and etc/systemd/system/multi-user.target.wants paths

I then copied the file from opt/shiny-server/config/systemd/shiny-server.service to the above locations. It started working. Not sure why this happened but I tried installing in multiple REHL EC2 instances and I ended up with same error.  Copying the file to the above paths fixed the issue.

**Comment by samchoraria** [comment]
https://github.com/rstudio/shiny-server/issues/316#issuecomment-326029648_

Same issue seen in AWS CentOS 7.8 EC2 Instance
using  https://download3.rstudio.org/centos6.3/x86_64/shiny-server-1.5.14.948-x86_64.rpm

**Comment by jcheng5** [comment]
@samchoraria Do you have /etc/systemd/system/shiny-server.service?

**Comment by samchoraria** [comment]
File was not in place after the rpm install finished; 
I had to manually copy  `/opt/shiny-server/config/systemd/shiny-server.service` to `/etc/systemd/system/shiny-server.service`
and then symlinked  to `/etc/systemd/system/multi-user.target.wants/shiny-server.service`
Exact same issue as  #316
