### ISSUE TITLE
Uncaught ReferenceError: preShinyInit is not defined

### ISSUE THREAD

**Issue by galen211** [rstudio/shiny-server#444]
I'm cross-posting this [issue](https://community.rstudio.com/t/shiny-server-400-uncaught-referenceerror-typeerror/67531) from the RStudio community site here because I'm not sure if it's a bug or not.  I'm running a shiny-server docker container on kubernetes behind a load balancer.  When I deploy my pod with shiny-server, I can see traffic routing into the pod and am getting partial page loads with a significant number of 400 errors on js and css assets.

In the console, I can see the aborted GET requests for the different assets along with a series of errors from `shiny-server-client.min.js` including `Uncaught ReferenceError: preShinyInit is not defined`

<img width="902" alt="Screen Shot 2020-05-26 at 2 41 19 PM" src="https://user-images.githubusercontent.com/4350963/82946274-0bb64380-9f6c-11ea-97ae-f2931c57175b.png">

Looking for help to understand this exception.

**Comment by jcheng5** [comment]
The TypeErrors and ReferenceErrors are just symptoms of the failed GET requests. The GET requests are likely failing because of https://github.com/rstudio/httpuv/issues/247. If you can get the load balancer to stop sending `Content-Length: 0` on proxied GET requests, great; otherwise, you'll have to either install httpuv from GitHub master (i.e. `remotes::install_github("rstudio/httpuv")`) or wait for the new httpuv release to hit CRAN. We are in the submission process already, so hopefully any day now?

**Comment by galen211** [comment]
Thanks this solved the error.  Appreciate the quick reply!
