### ISSUE TITLE
Is `shiny-server` able to run apps built with Dash, Flask, etc ?

### ISSUE THREAD

**Issue by avhz** [rstudio/shiny-server#575]
We have `shiny-server` set up to run R Shiny and Python Shiny apps, however I am interested to know if it can also serve Dash apps, for example. 

The "drag-and-drop" into `/srv/shiny-server` provides a tonne of convenience and it would be great if there was a way to do the same with a Dash or Flask app too. 

I have tried a minimal Dash app, but get "Internal Server Error" at the URL, because I assume `SockJSAdapter.py` is not able to pick the app up since it is not of the form `app = App(ui, server)`.

Any advice would be greatly appreciated !

**Comment by jcheng5** [comment]
No, sorry. Shiny Server is only designed for Shiny. Our enterprise hosting server, [Posit Connect](https://posit.co/products/enterprise/connect/), and cloud hosting server [Posit Connect Cloud](https://connect.posit.cloud/), work with additional frameworks including Dash and Flash.

I will note that Posit Connect uses a CLI command to deploy apps, and Posit Connect Cloud uses Git push-to-deploy. People generally find those options more convenient than `/srv/shiny-server` though, not less, since package dependency installation/isolation is handled automatically.
